[project]
name = "pykedex"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "httpx>=0.28.1",
    "pynput>=1.8.1",
    "pytest>=9.0.2",
    "rich>=14.2.0",
    "typer>=0.21.1",
]
